JakduchOSSSO: {
  url: "https://jakduch.github.io/os-sso/pkg/${ABI}",
  enabled: yes,
  mirror_type: "NONE",
  signature_type: "pubkey",
  pubkey: "/usr/local/etc/pkg/keys/jakduch-os-sso.pub",
  priority: 10
}
