#!/bin/sh
# Provisioner: deploy os-sso from /vagrant into the live OPNsense tree and vendor
# composer deps. Idempotent; runs on every `vagrant up`/`provision`.
set -e

# The puzzle/opnsense box runs provisioners as the unprivileged vagrant user;
# re-exec under sudo so we can write into /usr/local/opnsense.
[ "$(id -u)" -eq 0 ] || exec sudo sh "$0" "$@"

# The box boots without a default route / working DNS on the NAT interface.
# Restore both (runtime-only; harmless if already set) so pkg/composer work.
route -n get default >/dev/null 2>&1 || route add default 10.0.2.2 >/dev/null 2>&1 || true
if ! host -W2 pkg.opnsense.org >/dev/null 2>&1; then
    printf 'nameserver 10.0.2.3\nnameserver 8.8.8.8\n' > /etc/resolv.conf
fi

# Map the IdP hostname to the NAT gateway (the host) so the issuer string
# https://authentik.test:9443 is identical to what the host browser uses.
grep -q 'authentik.test' /etc/hosts || echo '10.0.2.2 authentik.test' >> /etc/hosts
grep -q 'keycloak.test' /etc/hosts || echo '10.0.2.2 keycloak.test' >> /etc/hosts

# Trust the lab CA so the OIDC RP (libcurl uses the /etc/ssl/certs capath) accepts
# the Authentik issuer's TLS cert. FreeBSD way: drop the CA in a trusted dir and
# rehash. Lab-only; a real deployment uses a publicly-trusted IdP cert.
LAB_CA=/home/vagrant/os-sso/test/idp/certs/ca.crt
if [ -f "$LAB_CA" ] && ! [ -f /usr/share/certs/trusted/os-sso-lab-ca.pem ]; then
    mkdir -p /usr/share/certs/trusted
    cp "$LAB_CA" /usr/share/certs/trusted/os-sso-lab-ca.pem
    certctl rehash >/dev/null 2>&1 && echo ">>> os-sso: lab CA trusted (certctl rehash)"
fi

# Source rsynced here by Vagrant's synced_folder (.. -> /home/vagrant/os-sso) on
# every `vagrant up`/`provision` -- vendored libs included. No manual push needed.
SRC=/home/vagrant/os-sso/src/opnsense/mvc/app
DST=/usr/local/opnsense/mvc/app
SSO_LIB="$DST/library/OPNsense/SSO"

echo ">>> os-sso: deploying source into the live tree"
mkdir -p "$DST/library/OPNsense/Auth/SSOProviders" \
         "$DST/controllers/OPNsense/SSO/Api"

cp -R "$SRC/library/OPNsense/SSO"                          "$DST/library/OPNsense/"
cp    "$SRC/library/OPNsense/Auth/SsoOidc.php"             "$DST/library/OPNsense/Auth/"
cp    "$SRC/library/OPNsense/Auth/SsoSaml.php"             "$DST/library/OPNsense/Auth/"
cp    "$SRC/library/OPNsense/Auth/SsoJwt.php"              "$DST/library/OPNsense/Auth/"
cp    "$SRC/library/OPNsense/Auth/SSOProviders/SsoProviderContainer.php" \
      "$DST/library/OPNsense/Auth/SSOProviders/"
cp -R "$SRC/controllers/OPNsense/SSO"                      "$DST/controllers/OPNsense/"
mkdir -p "$DST/models/OPNsense" "$DST/views/OPNsense"
cp -R "$SRC/models/OPNsense/SSO"                           "$DST/models/OPNsense/"
# Diagnostics + settings pages (volt views).
cp -R "$SRC/views/OPNsense/SSO"                            "$DST/views/OPNsense/"
# Re-pointed Logout menu item + two new menu entries -> drop the cached menu and
# the ACL cache so both rebuild.
rm -f /var/lib/php/tmp/opnsense_menu_cache.xml /tmp/opnsense_menu_cache.xml 2>/dev/null || true
rm -f /tmp/opnsense_acl_cache.json /var/lib/php/tmp/opnsense_acl_cache.json 2>/dev/null || true

echo ">>> os-sso: runtime libs"
# The appliance PHP CLI has no phar + allow_url_fopen=off, so composer cannot run
# here. Vendored sources + a hand-written PSR-4 autoloader are shipped in the tree
# (see vendor/autoload.php). Nothing to install if that autoloader is present.
if [ -f "$SSO_LIB/vendor/autoload.php" ]; then
    echo "    vendor/autoload.php present (pre-vendored on the host)"
else
    echo "!! vendor/autoload.php missing -- OIDC will fail until php-jwt is vendored"
fi

echo ">>> os-sso: deploying scripts, service templates and configd actions"
SVC_SRC=/home/vagrant/os-sso/src/opnsense
# Service templates: vpn.conf is generated from these by "configctl template reload",
# driven by the settings model (System > Access > SSO VPN web-auth).
mkdir -p /usr/local/opnsense/service/templates/OPNsense/SSO
cp -R "$SVC_SRC/service/templates/OPNsense/SSO/." /usr/local/opnsense/service/templates/OPNsense/SSO/
# vpn.conf is generated by the template above; seed one so a lab VM without any
# saved settings still has a usable file.
mkdir -p /usr/local/etc/sso
if [ ! -f /usr/local/etc/sso/vpn.conf ]; then
    # A heredoc, not printf with continued string literals: the continuations left
    # whitespace between them, so the shell passed three arguments rather than one
    # format -- which printed only the first chunk on FreeBSD 14 (a silently truncated
    # vpn.conf) and fails outright on 15, aborting the deploy under set -e.
    cat > /usr/local/etc/sso/vpn.conf <<'CONF'
PROFILE_default_PROTOCOL='oidc'
PROFILE_default_PROVIDER='keycloak'
PROFILE_default_PROVIDER_ENC='keycloak'
PROFILE_default_HOST='localhost:8443'
PROFILE_default_TIMEOUT='180'
PROFILE_default_ENFORCE_USERNAME='1'
DEFAULT_PROFILE='default'
CONF
fi
# Privileged helpers + configd actions (verdict writer, session expiry, cp template).
mkdir -p /usr/local/opnsense/scripts/OPNsense/SSO
cp "$SVC_SRC/scripts/OPNsense/SSO/vpn_verdict.sh" /usr/local/opnsense/scripts/OPNsense/SSO/
cp "$SVC_SRC/scripts/OPNsense/SSO/auth-user-pass-verify.sh" /usr/local/opnsense/scripts/OPNsense/SSO/
cp "$SVC_SRC/scripts/OPNsense/SSO/build_cp_template.sh" /usr/local/opnsense/scripts/OPNsense/SSO/
cp "$SVC_SRC/scripts/OPNsense/SSO/expire_sessions.php" /usr/local/opnsense/scripts/OPNsense/SSO/
cp "$SVC_SRC/scripts/OPNsense/SSO/vpn_kill.py" /usr/local/opnsense/scripts/OPNsense/SSO/
cp -R "$SVC_SRC/scripts/OPNsense/SSO/cp-portal" /usr/local/opnsense/scripts/OPNsense/SSO/
chmod 0755 /usr/local/opnsense/scripts/OPNsense/SSO/vpn_verdict.sh \
           /usr/local/opnsense/scripts/OPNsense/SSO/auth-user-pass-verify.sh \
           /usr/local/opnsense/scripts/OPNsense/SSO/build_cp_template.sh \
           /usr/local/opnsense/scripts/OPNsense/SSO/expire_sessions.php \
           /usr/local/opnsense/scripts/OPNsense/SSO/vpn_kill.py
cp "$SVC_SRC/service/conf/actions.d/actions_sso.conf" /usr/local/opnsense/service/conf/actions.d/
service configd restart >/dev/null 2>&1 || true

echo ">>> os-sso: restarting the WebGUI to pick up new classes"
/usr/local/etc/rc.restart_webgui >/dev/null 2>&1 || service php_fpm restart || true

echo ">>> os-sso: deployed. Files:"
ls "$DST/library/OPNsense/SSO"
echo ">>> vendor:"
ls "$SSO_LIB/vendor" 2>/dev/null || echo "  (no vendor dir -- composer step failed)"

# A real web-auth profile in the settings model, not just the seeded file above: the
# file is generated from the model by "configctl template reload", so a seed written by
# hand is erased by the next reload or reboot and the VPN hook then reports "no enabled
# web-auth profile". Seeding the file keeps a brand-new box usable; this keeps it usable.
if [ -f /home/vagrant/os-sso/test/vagrant/set_vpn_settings.php ]; then
    # The host is what goes into the WEB_AUTH url the OpenVPN client opens, so it has
    # to be the address the client's browser actually reaches -- the same origin the
    # suites use, not the loopback forward.
    php /home/vagrant/os-sso/test/vagrant/set_vpn_settings.php \
        profile=default enabled=1 protocol=oidc provider=keycloak \
        host="${SSO_LAN_IP:-192.168.60.10}" timeout=180 enforce_username=1 >/dev/null 2>&1 \
        && echo ">>> os-sso: web-auth profile 'default' in the settings model" \
        || echo ">>> os-sso: WARNING could not write the web-auth profile"
fi

# Lab network layout. Applied here rather than baked into the box, so the box stays a
# plain OPNsense and the lab owns its addressing: LAN on the second NIC (the host-only
# segment the captive portal and the host-side suites use -- the portal listens on
# 8000+zoneid of the zone interface, which a NAT forward cannot reach) and WAN on the
# Vagrant NAT, which keeps vagrant ssh and the WebGUI forward working.
SSO_LAN_IP="${SSO_LAN_IP:-192.168.60.10}"
php <<PHP
<?php
require_once("config.inc");
require_once("util.inc");
\$lan = &\$config['interfaces']['lan'];
\$wan = &\$config['interfaces']['wan'];
\$want = '${SSO_LAN_IP}';
if ((string)(\$lan['if'] ?? '') === 'em1' && (string)(\$lan['ipaddr'] ?? '') === \$want) {
    echo "layout already applied\n";
    exit(0);
}
\$lan['if'] = 'em1';
\$lan['ipaddr'] = \$want;
\$lan['subnet'] = '24';
unset(\$lan['ipaddrv6'], \$lan['subnetv6']);
\$wan['if'] = 'em0';
\$wan['ipaddr'] = 'dhcp';
write_config('os-sso lab: LAN on the host-only segment');
echo "layout applied\n";
PHP
configctl interface reconfigure lan >/dev/null 2>&1 || true
configctl interface reconfigure wan >/dev/null 2>&1 || true
echo ">>> os-sso: LAN ${SSO_LAN_IP} on em1, WAN dhcp on em0"

# Re-assert the IdP hostnames LAST. They are also written near the top, but OPNsense
# regenerates /etc/hosts whenever it reconfigures interfaces -- which happens during
# this very deploy -- so on a freshly built box the entries were gone by the time the
# suites ran and every login failed with "Could not resolve host: keycloak.test".
for h in authentik.test keycloak.test; do
    grep -q "$h" /etc/hosts || echo "10.0.2.2 $h" >> /etc/hosts
done
echo ">>> os-sso: IdP hostnames in /etc/hosts: $(grep -c -E 'authentik.test|keycloak.test' /etc/hosts)"
